// Auto-generated by `mcp__supabase__generate_typescript_types` against project xktiskyatbamqelqzoou.
// Re-run that tool whenever the schema changes and replace this file.
// DO NOT edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      landmarks: {
        Row: {
          category: string
          created_at: string
          description: string | null
          id: string
          lat: number
          lng: number
          name: string
        }
        Insert: {
          category: string
          created_at?: string
          description?: string | null
          id: string
          lat: number
          lng: number
          name: string
        }
        Update: {
          category?: string
          created_at?: string
          description?: string | null
          id?: string
          lat?: number
          lng?: number
          name?: string
        }
        Relationships: []
      }
      posts: {
        Row: {
          author_id: string
          body: string
          coords_lat: number
          coords_lng: number
          created_at: string
          id: number
          img: string
          landmark_id: string
          likes: number
          saves: number
          tags: string[]
        }
        Insert: {
          author_id: string
          body: string
          coords_lat: number
          coords_lng: number
          created_at?: string
          id?: number
          img: string
          landmark_id: string
          likes?: number
          saves?: number
          tags?: string[]
        }
        Update: {
          author_id?: string
          body?: string
          coords_lat?: number
          coords_lng?: number
          created_at?: string
          id?: number
          img?: string
          landmark_id?: string
          likes?: number
          saves?: number
          tags?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "posts_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_landmark_id_fkey"
            columns: ["landmark_id"]
            isOneToOne: false
            referencedRelation: "landmarks"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_emoji: string
          daily_posts_used: number
          display_name: string
          id: string
          joined_at: string
          level: number
          max_daily_posts: number
          post_count: number
          reaction_count: number
          total_points: number
          username: string
        }
        Insert: {
          avatar_emoji?: string
          daily_posts_used?: number
          display_name: string
          id: string
          joined_at?: string
          level?: number
          max_daily_posts?: number
          post_count?: number
          reaction_count?: number
          total_points?: number
          username: string
        }
        Update: {
          avatar_emoji?: string
          daily_posts_used?: number
          display_name?: string
          id?: string
          joined_at?: string
          level?: number
          max_daily_posts?: number
          post_count?: number
          reaction_count?: number
          total_points?: number
          username?: string
        }
        Relationships: []
      }
      reactions: {
        Row: {
          created_at: string
          id: number
          post_id: number
          type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: number
          post_id: number
          type: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: number
          post_id?: number
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
