// Auto-generated by `mcp__supabase__generate_typescript_types` against project xktiskyatbamqelqzoou.
// Re-run that tool whenever the schema changes and replace this file.
// DO NOT edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      landmarks: {
        Row: {
          category: string
          created_at: string
          description: string | null
          id: string
          lat: number
          lng: number
          name: string
        }
        Insert: {
          category: string
          created_at?: string
          description?: string | null
          id: string
          lat: number
          lng: number
          name: string
        }
        Update: {
          category?: string
          created_at?: string
          description?: string | null
          id?: string
          lat?: number
          lng?: number
          name?: string
        }
        Relationships: []
      }
      pets: {
        Row: {
          accessory: Json
          affinity: Json
          cleanliness: number
          coins: number
          created_at: string
          current_action: string
          exp: number
          expression: string
          favorability: number
          health: number
          hunger: number
          inventory: Json
          last_clean_time: string | null
          last_feed_time: string | null
          level: number
          mood: number
          name: string
          outfit: string
          pet_id: string
          skin: string
          species: string
          stage: string
          updated_at: string
          user_id: string
        }
        Insert: {
          accessory?: Json
          affinity?: Json
          cleanliness?: number
          coins?: number
          created_at?: string
          current_action?: string
          exp?: number
          expression?: string
          favorability?: number
          health?: number
          hunger?: number
          inventory?: Json
          last_clean_time?: string | null
          last_feed_time?: string | null
          level?: number
          mood?: number
          name?: string
          outfit?: string
          pet_id: string
          skin?: string
          species?: string
          stage?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          accessory?: Json
          affinity?: Json
          cleanliness?: number
          coins?: number
          created_at?: string
          current_action?: string
          exp?: number
          expression?: string
          favorability?: number
          health?: number
          hunger?: number
          inventory?: Json
          last_clean_time?: string | null
          last_feed_time?: string | null
          level?: number
          mood?: number
          name?: string
          outfit?: string
          pet_id?: string
          skin?: string
          species?: string
          stage?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      posts: {
        Row: {
          author_id: string
          body: string
          coords_lat: number
          coords_lng: number
          created_at: string
          id: number
          img: string
          landmark_id: string
          likes: number
          saves: number
          tags: string[]
        }
        Insert: {
          author_id: string
          body: string
          coords_lat: number
          coords_lng: number
          created_at?: string
          id?: number
          img: string
          landmark_id: string
          likes?: number
          saves?: number
          tags?: string[]
        }
        Update: {
          author_id?: string
          body?: string
          coords_lat?: number
          coords_lng?: number
          created_at?: string
          id?: number
          img?: string
          landmark_id?: string
          likes?: number
          saves?: number
          tags?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "posts_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "posts_landmark_id_fkey"
            columns: ["landmark_id"]
            isOneToOne: false
            referencedRelation: "landmarks"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_emoji: string
          daily_posts_used: number
          display_name: string
          id: string
          joined_at: string
          level: number
          max_daily_posts: number
          post_count: number
          reaction_count: number
          total_points: number
          username: string
        }
        Insert: {
          avatar_emoji?: string
          daily_posts_used?: number
          display_name: string
          id: string
          joined_at?: string
          level?: number
          max_daily_posts?: number
          post_count?: number
          reaction_count?: number
          total_points?: number
          username: string
        }
        Update: {
          avatar_emoji?: string
          daily_posts_used?: number
          display_name?: string
          id?: string
          joined_at?: string
          level?: number
          max_daily_posts?: number
          post_count?: number
          reaction_count?: number
          total_points?: number
          username?: string
        }
        Relationships: []
      }
      reactions: {
        Row: {
          created_at: string
          id: number
          post_id: number
          type: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: number
          post_id: number
          type: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: number
          post_id?: number
          type?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reactions_post_id_fkey"
            columns: ["post_id"]
            isOneToOne: false
            referencedRelation: "posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reactions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
